networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.196.0/24

services:
  xadmin-redis:
    image: bitnami/redis:7.4.1
    container_name: xadmin-redis
    restart: always
    networks:
      - net
    environment:
      - TZ=Asia/Shanghai
      - REDIS_PASSWORD=nineven
    healthcheck:
      test: "redis-cli -h 127.0.0.1 -a $$REDIS_PASSWORD info Replication"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  xadmin-server:
    container_name: xadmin-server
    restart: always
    tty: true
    command: start web
    image: nineaiyu/test1234:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /data/xadmin-server
    environment:
      - TZ=Asia/Shanghai
    networks:
      - net
    volumes: #需要设置 1001 权限，否则mysql会启动失败
      - ./:/data/xadmin-server
    external_links:
      - xadmin-redis:redis
    ulimits:
      core: 0
    ports:
      - "8896:8896"
    depends_on:
      - xadmin-redis
    healthcheck:
      test: "curl -fsL http://localhost:8896/api/common/api/health > /dev/null"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s

  xadmin-celery:
    container_name: xadmin-celery
    hostname: xadmin-celery
    ulimits:
      core: 0
    restart: always
    tty: true
    command: start task
    image: nineaiyu/test1234:
    working_dir: /data/xadmin-server
    environment:
      - TZ=Asia/Shanghai
    networks:
      - net
    volumes:
      - ./:/data/xadmin-server
    external_links:
      - xadmin-redis:redis
    depends_on:
      - xadmin-server
    healthcheck:
      test: "bash utils/check_celery.sh"
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

