name: Build and Push Base Image

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      - 'requirements.txt'
      - 'Dockerfile-base'

jobs:
  build-and-push-base-image:
    runs-on: ubuntu-latest

    steps:
      - name: Lock Pull Request
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"state":"pending", "description":"Action running, merge disabled", "context":"Lock PR"}' \
          "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}"

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract date
        id: vars
        run: echo "IMAGE_TAG=$(date +'%Y%m%d_%H%M%S')" >> $GITHUB_ENV

      - name: Extract repository name
        id: repo
        run: echo "REPO=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile-base
          tags: nineaiyu/${{ env.REPO }}-base:${{ env.IMAGE_TAG }}

      - name: Update Dockerfile
        run: |
          sed -i 's@nineaiyu/.*@nineaiyu/${{ env.REPO }}-base:${{ env.IMAGE_TAG }}@' Dockerfile

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add Dockerfile
          git commit -m "perf: Update Dockerfile with new base image tag"
          git push origin ${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}




  build-and-push-image:
    runs-on: ubuntu-latest
    needs: build-and-push-base-image
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract repository name
        id: repo
        run: echo "REPO=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: nineaiyu/${{ env.REPO }}
          tags: |
            type=semver,pattern={{version}}

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Update docker-compose.yml
        run: |
          sed -i 's@image: nineaiyu/.*@image: nineaiyu/${{ env.REPO }}:${{ env.IMAGE_TAG }}@' docker-compose.yml
          sed -i 's@image: nineaiyu/.*@image: nineaiyu/${{ env.REPO }}:${{ env.IMAGE_TAG }}@' docker-compose-sqlite.yml

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add docker-compose.yml docker-compose-sqlite.yml
          git commit -m "perf: Update docker-compose.yml with new image tag"
          git push origin ${{ github.event.pull_request.head.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Unlock Pull Request
        run: |
          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"state":"success", "description":"Action running, merge disabled", "context":"Lock PR"}' \
          "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}"