name: Build and Push Image

on:
  push:
    branches:
      - 'main'
      - 'dev'
    paths:
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'Dockerfile'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      #      - name: Lock Pull Request
      #        run: |
      #          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
      #          -d '{"state":"pending", "description":"Action running, merge disabled", "context":"Lock PR"}' \
      #          "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}"
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract repository name
        id: repo
        run: echo "REPO=$(basename ${{ github.repository }})" >> $GITHUB_ENV

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          file: Dockerfile
          tags: nineaiyu/${{ env.REPO }}:${{ env.IMAGE_TAG }}

#      - name: Unlock Pull Request
#        run: |
#          curl -X POST -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
#          -d '{"state":"success", "description":"Action running, merge disabled", "context":"Lock PR"}' \
#          "https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }}"
